---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)

data(rest_inspec)
# Clean the data. 
rest_insp_base = 
  rest_inspec %>% 
  filter(cuisine_description == "Asian", 
         !is.na(grade), 
         critical_flag == "Critical", 
         grade != "Not Yet Graded"
         ) %>% 
  select(dba, inspection_date, phone, score, street, grade, violation_code) %>%
  arrange(dba)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Score of Asian Restaurant Through Years

```{r}
# Make plotly scatterplot
rest_insp_base %>%
  mutate(text_label = str_c("Cuisine: ", dba, "\nGrade: ", grade)) %>% 
  plot_ly(
    x = ~inspection_date, y = ~score, type = "scatter", mode = "markers",
    color = ~grade, text = ~text_label, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### The Score Range of different Grade Rank

```{r}
# Make a plotly boxplot
rest_insp_base %>% 
  mutate(grade = fct_reorder(grade, score)) %>% 
  plot_ly(y = ~score, color = ~grade, type = "box", colors = "viridis")
```

### The Mean Score of Each Grade Group

```{r}
# Make a plotly barchart
rest_insp_base %>% 
  group_by(grade) %>% 
  summarize(mean = mean(score)) %>% 
  plot_ly(x = ~grade, y = ~mean, color = ~mean, type = "bar", colors = "viridis")
```

